// auto generated by go-ts, DO NOT EDIT

export type TNode = {
  id: string;
  host: string;
  name: string;
  user: string;
  port: number;
  status: string;
};

export type TGetAllReposRow = {
  repoId: number;
  name: string;
  owner: string;
  description: string;
  url: string;
  repoCreatedAt: string;
};

export type TGithubRepoResponse = {
  id: number;
  name: string;
  description: string;
  lastUpdated: string;
  owner: string;
};

export type TConnectRepoRequest = {
  name: string;
  owner: string;
};

export type TGetWorkflowRunsRow = {
  commitSha: string;
  repoName: string;
  pipelineId: string;
  workflowId: string;
  status: string;
  workflowName: string;
  branch: string;
  createdAt: string;
  duration: number;
};

export type TGetWorkflowRunByIdRow = {
  jobId: string;
  stepId: string;
  command: string;
  type: string;
  keys: string[];
  paths: string[];
  stepOrder: number;
  url: string;
  repoName: string;
  commitSha: string;
  branch: string;
  docker: string;
};

export type TGetStepsByJobIdRow = {
  type: string;
  id: string;
  name: string;
  command: string;
  status: string;
};

export type TGetCommandOutputsByStepIdRow = {
  id: string;
  stepId: string;
  stdout: string;
  type: string;
  createdAt: string;
};

export type TGetJobsByWorkflowIdRow = {
  id: string;
  name: string;
  status: string;
};

export type TTokenPair = {
  accessToken: string;
  refreshToken: string;
};

export type TGetUserByIdRow = {
  id: string;
  username: string;
  email: string;
  avatarUrl: string;
};

