# The build stage
FROM golang:1.22-bullseye as builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o go-api /app/cmd/agent/agent.go

# The run stage
FROM docker:dind
WORKDIR /app
COPY --from=builder /app/go-api .
EXPOSE 8888
CMD ["./go-api"]