/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SettingsLazyImport = createFileRoute('/settings')()
const ProjectsLazyImport = createFileRoute('/projects')()
const IndexLazyImport = createFileRoute('/')()
const PipelinesIndexLazyImport = createFileRoute('/pipelines/')()
const PipelinesPipelineIdLazyImport = createFileRoute(
  '/pipelines/$pipelineId',
)()

// Create/Update Routes

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const ProjectsLazyRoute = ProjectsLazyImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PipelinesIndexLazyRoute = PipelinesIndexLazyImport.update({
  path: '/pipelines/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pipelines/index.lazy').then((d) => d.Route),
)

const PipelinesPipelineIdLazyRoute = PipelinesPipelineIdLazyImport.update({
  path: '/pipelines/$pipelineId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pipelines/$pipelineId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/pipelines/$pipelineId': {
      id: '/pipelines/$pipelineId'
      path: '/pipelines/$pipelineId'
      fullPath: '/pipelines/$pipelineId'
      preLoaderRoute: typeof PipelinesPipelineIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdLazyRoute
  '/pipelines': typeof PipelinesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdLazyRoute
  '/pipelines': typeof PipelinesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/pipelines/$pipelineId': typeof PipelinesPipelineIdLazyRoute
  '/pipelines/': typeof PipelinesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/settings'
    | '/pipelines/$pipelineId'
    | '/pipelines'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/settings' | '/pipelines/$pipelineId' | '/pipelines'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/settings'
    | '/pipelines/$pipelineId'
    | '/pipelines/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  PipelinesPipelineIdLazyRoute: typeof PipelinesPipelineIdLazyRoute
  PipelinesIndexLazyRoute: typeof PipelinesIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  PipelinesPipelineIdLazyRoute: PipelinesPipelineIdLazyRoute,
  PipelinesIndexLazyRoute: PipelinesIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/projects",
        "/settings",
        "/pipelines/$pipelineId",
        "/pipelines/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/pipelines/$pipelineId": {
      "filePath": "pipelines/$pipelineId.lazy.tsx"
    },
    "/pipelines/": {
      "filePath": "pipelines/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
